# Generated by Django 4.2.16 on 2024-11-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0002_remove_inform_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inform',
            name='public',
        ),
    ]
