# Generated by Django 4.2.16 on 2025-12-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='集群名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('version', models.CharField(help_text='例如 v1.25.7+k3s1', max_length=50, verbose_name='集群版本')),
                ('kubeconfig', models.TextField(verbose_name='KubeConfig配置')),
                ('api_server', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Server地址')),
                ('import_status', models.CharField(choices=[('success', '导入成功'), ('failed', '导入失败'), ('pending', '导入中')], default='success', max_length=20, verbose_name='导入状态')),
                ('cluster_status', models.CharField(choices=[('running', '就绪'), ('abnormal', '异常'), ('unknown', '未知')], default='running', max_length=20, verbose_name='集群状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'K8s集群',
                'verbose_name_plural': 'K8s集群',
                'ordering': ['-created_at'],
            },
        ),
    ]
