# Generated by Django 4.2.16 on 2025-12-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusterInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='节点名称(主机名)')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('role', models.CharField(choices=[('master', 'Master'), ('worker', 'Worker')], default='worker', max_length=20, verbose_name='节点角色')),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('NotReady', 'NotReady'), ('Unknown', 'Unknown')], default='Unknown', max_length=50, verbose_name='节点状态')),
                ('cpu_cores', models.IntegerField(default=0, verbose_name='CPU逻辑核心数')),
                ('disk_total', models.CharField(default='0Gi', max_length=50, verbose_name='磁盘容量')),
                ('memory', models.CharField(max_length=50, verbose_name='内存配置')),
                ('os_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='操作系统')),
                ('kernel_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='内核版本')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='clusterInfo.cluster', verbose_name='所属集群')),
            ],
            options={
                'verbose_name': '集群节点',
                'verbose_name_plural': '集群节点',
                'unique_together': {('cluster', 'name')},
            },
        ),
    ]
