# Generated by Django 4.2.16 on 2025-12-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterInfo', '0002_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='cluster_status',
            field=models.CharField(choices=[('running', '就绪'), ('abnormal', '异常'), ('unknown', '下线')], default='running', max_length=20, verbose_name='集群状态'),
        ),
    ]
