# Generated by Django 4.2.16 on 2024-10-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdcRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64, verbose_name='机房地址')),
                ('username', models.CharField(max_length=32, verbose_name='机房负责人姓名')),
                ('username_phone', models.CharField(max_length=11, verbose_name='机房负责人手机号')),
                ('server_count', models.IntegerField(default=0, verbose_name='服务器数量')),
            ],
        ),
        migrations.CreateModel(
            name='IdcServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=10, verbose_name='主机名称')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='ip地址')),
                ('cpu_count', models.IntegerField(verbose_name='CPU个数')),
                ('memory_count', models.IntegerField(verbose_name='内存大小')),
                ('disk_count', models.IntegerField(verbose_name='磁盘大小')),
                ('function', models.TextField(verbose_name='服务器作用')),
                ('scan_status', models.IntegerField(choices=[(0, '异常'), (1, '故障'), (2, '正常')], default=2, max_length=10, verbose_name='扫描状态')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc.idcregion', verbose_name='')),
            ],
        ),
    ]
