# Generated by Django 4.2.16 on 2024-10-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcserver',
            name='scan_status',
            field=models.IntegerField(choices=[(0, '异常'), (1, '故障'), (2, '正常')], default=2, verbose_name='扫描状态'),
        ),
    ]
