# Generated by Django 4.2.16 on 2024-10-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0002_alter_idcserver_scan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcserver',
            name='memory_count',
            field=models.FloatField(verbose_name='内存大小'),
        ),
    ]
