# Generated by Django 4.2.16 on 2025-12-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0003_alter_idcserver_memory_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcserver',
            name='hostname',
            field=models.CharField(max_length=20, verbose_name='主机名称'),
        ),
    ]
