# Generated by Django 4.2.16 on 2025-12-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0004_alter_idcserver_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcregion',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='idcregion',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
    ]
